### ISSUE TITLE
causex todo list

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#327]
- [x] split between global and project settings
- [x] add title, description, and data source url to project settings
- [x] add new "new project" dialogue that includes prompt for title, description, and data source url, as well as an explanation about choosing folder
- [x] treat main subject, anything of type Wikidata Item, and all properties as =item[] not =value[]
- [x] add support for tags in entity definitions for properties
- [x] create dataset edges in kgtk output for project properties (title, description, url)
- [x] auto-generate missing properties and items
- [x] create dataset edges in kgtk output for auto-generated properties and items
- [x] create fully compliant statement edges
