### ISSUE TITLE
partial csv and csv download issues

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#519]
consolidating issues  #486, #501,  #504, and #509 into one issue.

- [x] #486 The downloaded CSV should have the following columns: Dataset_id,variable_id,variable,main_subject,main_subject_id,value,time,time_precision,country,country_id,country_cameo,admin1,admin2,admin3,region_coordinate,stated_in,stated_in_id,stated in,FactorClass,Relevance,Normalizer,Units,DocID
- [x] #501 the response is sometimes The response is only returning the header of the output table, without the rest of the table. For example:
- [x] #504 - inconsistent cameo codes
- [x]  #509 - cameo codes not shown in deployed version

**Comment by devowit** [comment]
@g1eb  can you deploy to website so i can check which of these are still problems?

**Comment by devowit** [comment]
@kyao  as far as i can tell all of these issues have been resolved on the currently deployed version. please confirm and close the issue.

**Comment by kyao** [comment]
All issues resolved

**Comment by devowit** [comment]
@kyao while fixing up the factor class prefix, i noticed  we have a column `country` and a column `main subject` aren't those the same thing? do we need both? if so, should i fill both with the country label? (right now main subject gets country label and country stays blank)

**Comment by kyao** [comment]
For CX main subject is always country. Fill both columns with the country label.
